<script setup lang="ts">
//clear sky icon (sun)
</script>
<template>
    <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        x="0px"
        y="0px"
        viewBox="0 0 180 100"
        enable-background="new 0 0 180 100"
        xml:space="preserve"
        class="w-32"
    >
        <g>
            <circle
                fill="#D61F6A"
                cx="90"
                cy="50"
                r="16.5"
            />
            <g>
                <line
                    fill="none"
                    stroke="#D61F6A"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="90"
                    y1="21.1"
                    x2="90"
                    y2="28.4"
                />
                <line
                    fill="none"
                    stroke="#D61F6A"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="90"
                    y1="71.6"
                    x2="90"
                    y2="78.9"
                />
            </g>
            <g>
                <line
                    fill="none"
                    stroke="#D61F6A"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="118.9"
                    y1="49.6"
                    x2="111.6"
                    y2="49.6"
                />
                <line
                    fill="none"
                    stroke="#D61F6A"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="68.4"
                    y1="49.6"
                    x2="61.1"
                    y2="49.6"
                />
            </g>
            <g>
                <line
                    fill="none"
                    stroke="#D61F6A"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="110.3"
                    y1="29.3"
                    x2="105.1"
                    y2="34.5"
                />
                <line
                    fill="none"
                    stroke="#D61F6A"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="74.6"
                    y1="65"
                    x2="69.5"
                    y2="70.2"
                />
            </g>
            <g>
                <line
                    fill="none"
                    stroke="#D61F6A"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="110.5"
                    y1="69.9"
                    x2="105.4"
                    y2="64.8"
                />
                <line
                    fill="none"
                    stroke="#D61F6A"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="74.9"
                    y1="34.2"
                    x2="69.7"
                    y2="29.1"
                />
            </g>
        </g>
    </svg>
</template>