<script setup lang="ts">
//rain
</script>
<template>
    <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        x="0px"
        y="0px"
        viewBox="0 0 180 100"
        enable-background="new 0 0 180 100"
        xml:space="preserve"
        class="w-32"
    >
        <g>
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="65"
                y1="66"
                x2="65"
                y2="71.9"
            />
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="86.5"
                y1="66"
                x2="86.5"
                y2="71.9"
            />
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="76.6"
                y1="71.9"
                x2="76.6"
                y2="77.9"
            />
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="99.9"
                y1="71.3"
                x2="99.9"
                y2="77.2"
            />
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="58.4"
                y1="74.9"
                x2="58.4"
                y2="80.8"
            />
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="69.6"
                y1="81.9"
                x2="69.6"
                y2="87.8"
            />
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="91.1"
                y1="77.9"
                x2="91.1"
                y2="83.8"
            />
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="113.3"
                y1="66"
                x2="113.3"
                y2="71.9"
            />
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="109.1"
                y1="79"
                x2="109.1"
                y2="84.9"
            />
            <circle
                fill="#D61F6A"
                cx="114.6"
                cy="31.7"
                r="19.5"
            />
            <path
                fill="#FFFFFF"
                d="M121.2,51c0,8-4.8,10.3-14,10.3c-0.4,0-46.8,0-47.3,0C51.3,61.4,46,59,46,51c0-8,6.2-14.6,14-15.2v-0.1 c0-8.5,6.9-15.3,15.3-15.3c3.3,0,6.3,1,8.7,2.7c2.8-2.9,6.7-4.8,11.1-4.8c8.5,0,15.3,6.9,15.3,15.3c0,0.9-0.1,1.8-0.2,2.6 C116.5,38.2,121.2,44.1,121.2,51z"
            />
        </g>
    </svg>
</template>