<script setup lang="ts">
// snow
</script>
<template>
    <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        x="0px"
        y="0px"
        viewBox="0 0 180 100"
        enable-background="new 0 0 180 100"
        xml:space="preserve"
        class="w-32"
    >
        <g>
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="90"
                y1="69.9"
                x2="90"
                y2="30.1"
            />
            <g>	
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="93.6"
                    y1="75"
                    x2="90"
                    y2="69.9"
                />
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="86.4"
                    y1="75"
                    x2="90"
                    y2="69.9"
                />
            </g>
            <g>
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="86.4"
                    y1="25"
                    x2="90"
                    y2="30.1"
                />
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="93.6"
                    y1="25"
                    x2="90"
                    y2="30.1"
                />
            </g>
        </g>
        <g>
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="70.1"
                y1="50"
                x2="109.9"
                y2="50"
            />
            <g>
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="65"
                    y1="53.6"
                    x2="70.1"
                    y2="50"
                />
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="65"
                    y1="46.4"
                    x2="70.1"
                    y2="50"
                />
            </g>
            <g>
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="115"
                    y1="46.4"
                    x2="109.9"
                    y2="50"
                />
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="115"
                    y1="53.6"
                    x2="109.9"
                    y2="50"
                />
            </g>
        </g>
        <g>
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="76.3"
                y1="64.1"
                x2="104.4"
                y2="36"
            />
            <g>
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="75.2"
                    y1="70.3"
                    x2="76.3"
                    y2="64.1"
                />
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="70.1"
                    y1="65.2"
                    x2="76.3"
                    y2="64.1"
                />
            </g>
            <g>
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="105.5"
                    y1="29.8"
                    x2="104.4"
                    y2="36"
                />
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="110.6"
                    y1="34.8"
                    x2="104.4"
                    y2="36"
                />
            </g>
        </g>
        <g>
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="76.3"
                y1="36"
                x2="104.4"
                y2="64.1"
            />
            <g>
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="70.1"
                    y1="34.9"
                    x2="76.3"
                    y2="35.9"
                />
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="75.2"
                    y1="29.8"
                    x2="76.3"
                    y2="35.9"
                />
            </g>
            <g>
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="110.6"
                    y1="65.2"
                    x2="104.4"
                    y2="64.1"
                />
                <line
                    fill="none"
                    stroke="#FFFFFF"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-miterlimit="10"
                    x1="105.5"
                    y1="70.2"
                    x2="104.4"
                    y2="64.1"
                />
            </g>
        </g>
    </svg>
</template>