<script setup lang="ts">
// mist icon
</script>
<template>    
    <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        x="0px"
        y="0px"
        viewBox="0 0 180 100"
        enable-background="new 0 0 180 100"
        xml:space="preserve"
        class="w-32"
    >
        <g>		
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="43.2"
                y1="27.9"
                x2="98.4"
                y2="27.9"
            />
        
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="64.9"
                y1="35.3"
                x2="144.1"
                y2="35.3"
            />
        
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="35.9"
                y1="42.7"
                x2="86.2"
                y2="42.7"
            />
        
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="60.6"
                y1="50.1"
                x2="128.8"
                y2="50.1"
            />
        
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="48.3"
                y1="57.5"
                x2="117.4"
                y2="57.5"
            />
        
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="85.5"
                y1="64.9"
                x2="137.4"
                y2="64.9"
            />
        
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="93.1"
                y1="42.7"
                x2="107.8"
                y2="42.7"
            />
        
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="64.7"
                y1="64.9"
                x2="79.4"
                y2="64.9"
            />
        
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="105.6"
                y1="27.9"
                x2="120.3"
                y2="27.9"
            />
        
            <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-miterlimit="10"
                x1="41.5"
                y1="72.1"
                x2="107.8"
                y2="72.1"
            />
        </g>
    </svg>
</template>